import type { Project } from '@/features/projects/types/project'

const projectSamples: Project[] = [
  {
    id: 'torre-litoral',
    name: 'Torre Litoral',
    client: 'Inmobiliaria Litoral',
    clientContact: 'Lucía Castillo',
    projectType: 'Residential',
    address: 'Av. Vallarta 2450, Americana, Guadalajara, Jal.',
    latitude: 20.6742,
    longitude: -103.3848,
    budget: 12800000,
    spent: 7424000,
    startDate: '2025-01-15',
    estimatedCompletion: '2026-02-28',
    progress: 58,
    manager: 'Javier Moreno',
    assignedEmployees: ['Javier Moreno', 'Daniela Vega', 'Óscar Valdés', 'Mateo Silva'],
    materials: ['Concrete C35', 'Rebar No. 4', 'Structural steel', 'Facade glass'],
    equipment: ['Tower crane TC-04', 'Concrete pump CP-12', 'Scissor lift SL-08'],
    status: 'Active',
    description: '64-unit residential tower with two underground parking levels and a shared rooftop amenity floor.',
    timeline: [
      { id: 'tl-1', title: 'Foundation completed', description: 'Basement foundation and waterproofing approved.', date: '2025-04-28', status: 'completed' },
      { id: 'tl-2', title: 'Structure in progress', description: 'Level 10 structural frame currently underway.', date: '2025-06-20', status: 'current' },
      { id: 'tl-3', title: 'Facade installation', description: 'Begin curtain wall installation after structure sign-off.', date: '2025-08-12', status: 'upcoming' },
    ],
    photos: [
      { id: 'tl-p1', url: 'https://images.unsplash.com/photo-1541888946425-d81bb19240f5?auto=format&fit=crop&w=900&q=80', alt: 'Tower construction site with crane', label: 'Structure progress' },
      { id: 'tl-p2', url: 'https://images.unsplash.com/photo-1503387762-592deb58ef4e?auto=format&fit=crop&w=900&q=80', alt: 'Architectural plans on a desk', label: 'Design coordination' },
      { id: 'tl-p3', url: 'https://images.unsplash.com/photo-1504307651254-35680f356dfd?auto=format&fit=crop&w=900&q=80', alt: 'Construction workers on a site', label: 'Site operations' },
      { id: 'tl-p4', url: 'https://images.unsplash.com/photo-1590496793929-36417d3117de?auto=format&fit=crop&w=900&q=80', alt: 'Interior construction work', label: 'Interior works' },
    ],
    documents: [
      { id: 'tl-d1', name: 'Construction schedule - Rev 04', type: 'PDF', size: '2.4 MB', updatedAt: '2025-06-18' },
      { id: 'tl-d2', name: 'Structural plans - Level 10', type: 'PDF', size: '8.1 MB', updatedAt: '2025-06-14' },
      { id: 'tl-d3', name: 'Budget control June 2025', type: 'XLSX', size: '1.1 MB', updatedAt: '2025-06-12' },
    ],
    dailyLogs: [
      { id: 'tl-l1', date: '2025-06-18', author: 'Javier Moreno', weather: 'Clear, 27°C', crew: 42, summary: 'Level 10 slab reinforcement completed. Concrete pour scheduled for tomorrow morning.', blockers: 'Awaiting final MEP sleeve inspection.' },
      { id: 'tl-l2', date: '2025-06-17', author: 'Daniela Vega', weather: 'Partly cloudy, 25°C', crew: 39, summary: 'Rebar placement continued on Level 10. Material delivery received in full.', blockers: 'None reported.' },
    ],
    tasks: [
      { id: 'tl-t1', title: 'Approve Level 10 concrete pour', assignee: 'Javier Moreno', dueDate: '2025-06-20', priority: 'High', completed: false },
      { id: 'tl-t2', title: 'Upload MEP coordination drawings', assignee: 'Daniela Vega', dueDate: '2025-06-21', priority: 'Medium', completed: false },
      { id: 'tl-t3', title: 'Confirm facade supplier delivery', assignee: 'Mateo Silva', dueDate: '2025-06-24', priority: 'Medium', completed: false },
    ],
    inspections: [
      { id: 'tl-i1', title: 'Rebar and formwork inspection', area: 'Level 10 slab', dueDate: '2025-06-19', completed: false, owner: 'Óscar Valdés' },
      { id: 'tl-i2', title: 'Waterproofing sign-off', area: 'Basement B2', dueDate: '2025-05-30', completed: true, owner: 'Daniela Vega' },
    ],
    safetyIncidents: [
      { id: 'tl-s1', title: 'Minor material handling injury', date: '2025-05-22', severity: 'Low', status: 'Closed' },
    ],
    progressHistory: [
      { label: 'Jan', planned: 8, actual: 7 },
      { label: 'Feb', planned: 15, actual: 14 },
      { label: 'Mar', planned: 24, actual: 23 },
      { label: 'Apr', planned: 34, actual: 31 },
      { label: 'May', planned: 46, actual: 48 },
      { label: 'Jun', planned: 56, actual: 58 },
    ],
  },
  {
    id: 'plaza-alameda',
    name: 'Plaza Alameda Expansion',
    client: 'Plaza Alameda Operaciones',
    clientContact: 'Fernando Aguirre',
    projectType: 'Commercial',
    address: 'Av. Mariano Otero 1500, Chapalita, Guadalajara, Jal.',
    latitude: 20.6539,
    longitude: -103.3974,
    budget: 6400000,
    spent: 3840000,
    startDate: '2025-03-03',
    estimatedCompletion: '2025-11-21',
    progress: 61,
    manager: 'Ana Ruiz',
    assignedEmployees: ['Ana Ruiz', 'Miguel García', 'Sofía Ramos'],
    materials: ['Steel framing', 'Drywall', 'Porcelain tile', 'HVAC ducting'],
    equipment: ['Boom lift BL-02', 'Forklift FL-03', 'Generator GP-10'],
    status: 'Active',
    description: 'Retail expansion and major systems upgrade across the east wing of the operating shopping center.',
    timeline: [
      { id: 'pa-1', title: 'Site mobilization', description: 'Temporary works and safety perimeter established.', date: '2025-03-03', status: 'completed' },
      { id: 'pa-2', title: 'MEP coordination', description: 'Existing services coordination in progress.', date: '2025-06-18', status: 'current' },
      { id: 'pa-3', title: 'Tenant handover', description: 'Phased handover planned for November.', date: '2025-11-21', status: 'upcoming' },
    ],
    photos: [
      { id: 'pa-p1', url: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=900&q=80', alt: 'Modern commercial building exterior', label: 'East wing' },
      { id: 'pa-p2', url: 'https://images.unsplash.com/photo-1556761175-b413da4baf72?auto=format&fit=crop&w=900&q=80', alt: 'Team reviewing project plans', label: 'Coordination meeting' },
      { id: 'pa-p3', url: 'https://images.unsplash.com/photo-1581094794329-c8112a89af12?auto=format&fit=crop&w=900&q=80', alt: 'Engineer at a construction site', label: 'Site inspection' },
    ],
    documents: [{ id: 'pa-d1', name: 'Tenant coordination pack', type: 'PDF', size: '5.8 MB', updatedAt: '2025-06-16' }],
    dailyLogs: [{ id: 'pa-l1', date: '2025-06-18', author: 'Ana Ruiz', weather: 'Sunny, 29°C', crew: 28, summary: 'Mechanical subcontractor completed the east corridor duct survey.', blockers: 'Night access window pending client confirmation.' }],
    tasks: [{ id: 'pa-t1', title: 'Confirm tenant access windows', assignee: 'Ana Ruiz', dueDate: '2025-06-20', priority: 'High', completed: false }],
    inspections: [{ id: 'pa-i1', title: 'Fire protection inspection', area: 'East wing', dueDate: '2025-06-23', completed: false, owner: 'Sofía Ramos' }],
    safetyIncidents: [],
    progressHistory: [{ label: 'Mar', planned: 7, actual: 6 }, { label: 'Apr', planned: 22, actual: 20 }, { label: 'May', planned: 41, actual: 44 }, { label: 'Jun', planned: 57, actual: 61 }],
  },
  {
    id: 'centro-logistico-oriente',
    name: 'Centro Logístico Oriente',
    client: 'Logística Oriente',
    clientContact: 'Sergio Navarro',
    projectType: 'Industrial',
    address: 'Av. Miguel Alemán 6500, Apodaca, Nuevo León',
    latitude: 25.7785,
    longitude: -100.1887,
    budget: 21500000,
    spent: 3010000,
    startDate: '2025-08-04',
    estimatedCompletion: '2026-08-28',
    progress: 14,
    manager: 'Carlos Méndez',
    assignedEmployees: ['Carlos Méndez', 'Pablo Reyes', 'María León'],
    materials: ['Precast concrete', 'Structural steel', 'Insulated panels'],
    equipment: ['Crawler crane CC-01', 'Telehandler TH-05'],
    status: 'Planning',
    description: 'New distribution center with automated storage zones, loading yards, and administrative offices.',
    timeline: [{ id: 'clo-1', title: 'Pre-construction planning', description: 'Permits, procurement, and site logistics being coordinated.', date: '2025-06-18', status: 'current' }, { id: 'clo-2', title: 'Groundbreaking', description: 'Target date for first site works.', date: '2025-08-04', status: 'upcoming' }],
    photos: [{ id: 'clo-p1', url: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&w=900&q=80', alt: 'Industrial warehouse exterior', label: 'Reference site' }],
    documents: [{ id: 'clo-d1', name: 'Pre-construction scope', type: 'PDF', size: '3.2 MB', updatedAt: '2025-06-18' }],
    dailyLogs: [],
    tasks: [{ id: 'clo-t1', title: 'Finalize site logistics plan', assignee: 'Pablo Reyes', dueDate: '2025-06-27', priority: 'High', completed: false }],
    inspections: [],
    safetyIncidents: [],
    progressHistory: [{ label: 'Jun', planned: 12, actual: 14 }],
  },
  {
    id: 'hotel-central-reforma',
    name: 'Hotel Central Reforma',
    client: 'Hotel Central Reforma',
    clientContact: 'Patricia León',
    projectType: 'Renovation',
    address: 'Paseo de la Reforma 220, Juárez, CDMX',
    latitude: 19.427,
    longitude: -99.168,
    budget: 8900000,
    spent: 8455000,
    startDate: '2024-10-07',
    estimatedCompletion: '2025-07-18',
    progress: 91,
    manager: 'Lucía Castillo',
    assignedEmployees: ['Lucía Castillo', 'Daniela Vega', 'Javier Moreno'],
    materials: ['Porcelain tile', 'Millwork', 'LED fixtures', 'Acoustic panels'],
    equipment: ['Material lift ML-02', 'Portable generator PG-04'],
    status: 'At Risk',
    description: 'Phased lobby and guest-room renovation delivered through controlled night-time work windows.',
    timeline: [{ id: 'hcr-1', title: 'Guest rooms complete', description: '84 room renovation scope accepted.', date: '2025-05-16', status: 'completed' }, { id: 'hcr-2', title: 'Lobby finishes', description: 'Final finishes are behind the baseline by five days.', date: '2025-06-18', status: 'current' }, { id: 'hcr-3', title: 'Final handover', description: 'Target completion after close-out walk.', date: '2025-07-18', status: 'upcoming' }],
    photos: [{ id: 'hcr-p1', url: 'https://images.unsplash.com/photo-1564501049412-61c2a3083791?auto=format&fit=crop&w=900&q=80', alt: 'Modern hotel lobby interior', label: 'Lobby finishes' }, { id: 'hcr-p2', url: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=900&q=80', alt: 'Modern interior renovation', label: 'Guest room' }],
    documents: [{ id: 'hcr-d1', name: 'Close-out punch list', type: 'PDF', size: '1.8 MB', updatedAt: '2025-06-17' }],
    dailyLogs: [{ id: 'hcr-l1', date: '2025-06-18', author: 'Lucía Castillo', weather: 'Indoor works', crew: 31, summary: 'Lobby millwork installation continued in the north reception zone.', blockers: 'One custom lighting fixture delayed by supplier.' }],
    tasks: [{ id: 'hcr-t1', title: 'Resolve lighting fixture delay', assignee: 'Lucía Castillo', dueDate: '2025-06-20', priority: 'High', completed: false }],
    inspections: [{ id: 'hcr-i1', title: 'Final fire and life safety walk', area: 'Lobby and public areas', dueDate: '2025-06-30', completed: false, owner: 'Daniela Vega' }],
    safetyIncidents: [{ id: 'hcr-s1', title: 'Blocked egress during night shift', date: '2025-06-11', severity: 'Medium', status: 'Investigating' }],
    progressHistory: [{ label: 'Mar', planned: 66, actual: 65 }, { label: 'Apr', planned: 76, actual: 75 }, { label: 'May', planned: 86, actual: 87 }, { label: 'Jun', planned: 95, actual: 91 }],
  },
  {
    id: 'campus-metropolitano',
    name: 'Campus Metropolitano',
    client: 'Universidad Metropolitana',
    clientContact: 'Óscar Valdés',
    projectType: 'Infrastructure',
    address: 'Av. Universidad 1870, Copilco, CDMX',
    latitude: 19.3271,
    longitude: -99.1747,
    budget: 15400000,
    spent: 10500000,
    startDate: '2025-02-10',
    estimatedCompletion: '2025-12-12',
    progress: 68,
    manager: 'Miguel García',
    assignedEmployees: ['Miguel García', 'Sofía Ramos', 'Mateo Silva'],
    materials: ['Rebar No. 5', 'Concrete C30', 'Aluminum windows'],
    equipment: ['Backhoe BH-07', 'Compactor CP-09', 'Boom lift BL-05'],
    status: 'Active',
    description: 'Campus expansion with new learning spaces, student services, and accessible outdoor circulation.',
    timeline: [{ id: 'cm-1', title: 'Structural frame', description: 'Main learning wing frame completed.', date: '2025-06-06', status: 'completed' }, { id: 'cm-2', title: 'Envelope installation', description: 'Windows and exterior envelope are progressing.', date: '2025-06-18', status: 'current' }, { id: 'cm-3', title: 'Commissioning', description: 'Systems commissioning planned before winter break.', date: '2025-11-10', status: 'upcoming' }],
    photos: [{ id: 'cm-p1', url: 'https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&w=900&q=80', alt: 'Modern campus interior workspace', label: 'Learning wing' }],
    documents: [{ id: 'cm-d1', name: 'Accessibility review package', type: 'PDF', size: '4.6 MB', updatedAt: '2025-06-15' }],
    dailyLogs: [{ id: 'cm-l1', date: '2025-06-17', author: 'Miguel García', weather: 'Cloudy, 22°C', crew: 36, summary: 'Window installation completed on the north elevation.', blockers: 'Waiting for revised accessibility detail at entrance B.' }],
    tasks: [{ id: 'cm-t1', title: 'Review entrance B detail', assignee: 'Sofía Ramos', dueDate: '2025-06-21', priority: 'Medium', completed: false }],
    inspections: [{ id: 'cm-i1', title: 'Envelope water test', area: 'North elevation', dueDate: '2025-06-25', completed: false, owner: 'Mateo Silva' }],
    safetyIncidents: [],
    progressHistory: [{ label: 'Mar', planned: 35, actual: 32 }, { label: 'Apr', planned: 48, actual: 46 }, { label: 'May', planned: 59, actual: 61 }, { label: 'Jun', planned: 66, actual: 68 }],
  },
]

export function getProjects(): Project[] {
  return projectSamples
}

export function getProjectById(id: string): Project | undefined {
  return projectSamples.find((project) => project.id === id)
}
