import type { Customer } from '@/features/crm/types/customer'

const customerSamples: Customer[] = [
  {
    id: 'grupo-arista',
    company: 'Grupo Arista Desarrollos',
    contact: 'Mariana Torres',
    phone: '+52 55 1842 9031',
    email: 'mariana.torres@arista.com.mx',
    address: 'Av. Paseo de la Reforma 412, Cuauhtémoc, CDMX',
    rfc: 'GAD180426KQ2',
    projectType: 'Comercial',
    leadSource: 'Referido',
    status: 'Active',
    assignedSalesperson: 'Ana Ruiz',
    notes: 'Cuenta estratégica. Dos proyectos activos y uno en etapa de anteproyecto.',
    createdAt: '2024-02-12',
    lastContact: '2025-06-18',
    timeline: [
      { id: 'ar-1', type: 'meeting', title: 'Reunión de avance', description: 'Revisión de alcance para Torre Reforma Norte.', date: '2025-06-18', author: 'Ana Ruiz' },
      { id: 'ar-2', type: 'quote', title: 'Cotización aprobada', description: 'Cotización Q-2025-041 aceptada por el cliente.', date: '2025-06-05', author: 'Ana Ruiz' },
      { id: 'ar-3', type: 'email', title: 'Documentos contractuales', description: 'Se compartió el paquete de documentación inicial.', date: '2025-05-28', author: 'Miguel García' },
    ],
  },
  {
    id: 'constructora-norte',
    company: 'Constructora Norte 360',
    contact: 'Javier Moreno',
    phone: '+52 81 2468 1170',
    email: 'javier.moreno@norte360.mx',
    address: 'Calzada del Valle 305, San Pedro Garza García, NL',
    rfc: 'CN360210MT7',
    projectType: 'Industrial',
    leadSource: 'Evento',
    status: 'Proposal',
    assignedSalesperson: 'Carlos Méndez',
    notes: 'Interesados en nave industrial de 18,000 m² con entrega por fases.',
    createdAt: '2025-01-20',
    lastContact: '2025-06-17',
    timeline: [
      { id: 'cn-1', type: 'email', title: 'Alcance actualizado', description: 'El cliente envió especificaciones para la segunda fase.', date: '2025-06-17', author: 'Carlos Méndez' },
      { id: 'cn-2', type: 'quote', title: 'Propuesta enviada', description: 'Propuesta comercial enviada para revisión.', date: '2025-06-12', author: 'Carlos Méndez' },
    ],
  },
  {
    id: 'inmobiliaria-litoral',
    company: 'Inmobiliaria Litoral',
    contact: 'Lucía Castillo',
    phone: '+52 33 3190 4421',
    email: 'lucia.castillo@litoral.mx',
    address: 'Av. Vallarta 2450, Americana, Guadalajara, Jal.',
    rfc: 'ILI190712P81',
    projectType: 'Residencial',
    leadSource: 'Sitio web',
    status: 'Qualified',
    assignedSalesperson: 'Miguel García',
    notes: 'Desarrollo residencial de 64 unidades. Pendiente visita técnica.',
    createdAt: '2025-04-08',
    lastContact: '2025-06-16',
    timeline: [
      { id: 'il-1', type: 'call', title: 'Llamada de calificación', description: 'Se validó presupuesto, ubicación y fecha objetivo.', date: '2025-06-16', author: 'Miguel García' },
      { id: 'il-2', type: 'note', title: 'Cliente calificado', description: 'Cumple criterios de oportunidad prioritaria.', date: '2025-06-16', author: 'Miguel García' },
    ],
  },
  {
    id: 'grupo-senda',
    company: 'Grupo Senda Urbana',
    contact: 'Roberto Salas',
    phone: '+52 55 6721 0388',
    email: 'roberto.salas@sendaurbana.com',
    address: 'Bosque de Alisos 25, Bosques de las Lomas, CDMX',
    rfc: 'GSU170918LJ5',
    projectType: 'Infraestructura',
    leadSource: 'Prospección',
    status: 'Lead',
    assignedSalesperson: 'Ana Ruiz',
    notes: 'Oportunidad inicial para adecuación de corredor urbano.',
    createdAt: '2025-06-11',
    lastContact: '2025-06-13',
    timeline: [
      { id: 'gs-1', type: 'email', title: 'Primer contacto', description: 'Se envió presentación corporativa y capacidades.', date: '2025-06-13', author: 'Ana Ruiz' },
    ],
  },
  {
    id: 'hotel-central',
    company: 'Hotel Central Reforma',
    contact: 'Patricia León',
    phone: '+52 55 5080 2294',
    email: 'patricia.leon@hotelcentral.mx',
    address: 'Paseo de la Reforma 220, Juárez, CDMX',
    rfc: 'HCR2003068F4',
    projectType: 'Remodelación',
    leadSource: 'Referido',
    status: 'Active',
    assignedSalesperson: 'Carlos Méndez',
    notes: 'Remodelación de lobby y 84 habitaciones, ejecución nocturna.',
    createdAt: '2024-11-19',
    lastContact: '2025-06-12',
    timeline: [
      { id: 'hc-1', type: 'meeting', title: 'Comité de proyecto', description: 'Se aprobó el plan de trabajo para la siguiente etapa.', date: '2025-06-12', author: 'Carlos Méndez' },
      { id: 'hc-2', type: 'call', title: 'Seguimiento de obra', description: 'Se confirmó el calendario de intervención nocturna.', date: '2025-06-09', author: 'Carlos Méndez' },
    ],
  },
  {
    id: 'parques-del-valle',
    company: 'Parques del Valle',
    contact: 'Elena Ríos',
    phone: '+52 81 1920 7754',
    email: 'elena.rios@parquesdelvalle.mx',
    address: 'Av. José Vasconcelos 890, Del Valle, San Pedro, NL',
    rfc: 'PDV210421QW8',
    projectType: 'Residencial',
    leadSource: 'Redes sociales',
    status: 'Inactive',
    assignedSalesperson: 'Lucía Castillo',
    notes: 'Proyecto pausado por decisión de inversión. Revisar en Q4.',
    createdAt: '2024-09-03',
    lastContact: '2025-04-22',
    timeline: [
      { id: 'pv-1', type: 'note', title: 'Oportunidad pausada', description: 'El cliente solicita retomar conversaciones en octubre.', date: '2025-04-22', author: 'Lucía Castillo' },
    ],
  },
  {
    id: 'plaza-alameda',
    company: 'Plaza Alameda Operaciones',
    contact: 'Fernando Aguirre',
    phone: '+52 33 2871 4409',
    email: 'fernando.aguirre@plazaalameda.mx',
    address: 'Av. Mariano Otero 1500, Chapalita, Guadalajara, Jal.',
    rfc: 'PAO180822D12',
    projectType: 'Comercial',
    leadSource: 'Evento',
    status: 'Active',
    assignedSalesperson: 'Miguel García',
    notes: 'Mantenimiento mayor y ampliación de áreas comerciales.',
    createdAt: '2024-06-27',
    lastContact: '2025-06-10',
    timeline: [
      { id: 'pa-1', type: 'email', title: 'Cambio de presupuesto', description: 'Se compartió la actualización de costos de materiales.', date: '2025-06-10', author: 'Miguel García' },
    ],
  },
  {
    id: 'clinica-san-angel',
    company: 'Clínica San Ángel',
    contact: 'Daniela Vega',
    phone: '+52 55 4408 3160',
    email: 'daniela.vega@clinicasanangel.mx',
    address: 'Av. Revolución 1240, San Ángel, CDMX',
    rfc: 'CSA220114NQ6',
    projectType: 'Remodelación',
    leadSource: 'Sitio web',
    status: 'Qualified',
    assignedSalesperson: 'Ana Ruiz',
    notes: 'Adecuación de área quirúrgica con ventanas de operación restringidas.',
    createdAt: '2025-05-19',
    lastContact: '2025-06-09',
    timeline: [
      { id: 'csa-1', type: 'meeting', title: 'Visita técnica agendada', description: 'Visita confirmada para validar instalaciones existentes.', date: '2025-06-09', author: 'Ana Ruiz' },
    ],
  },
  {
    id: 'logistica-oriente',
    company: 'Logística Oriente',
    contact: 'Sergio Navarro',
    phone: '+52 81 3810 6245',
    email: 'sergio.navarro@logisticaoriente.com',
    address: 'Av. Miguel Alemán 6500, Apodaca, NL',
    rfc: 'LOR190531MZ3',
    projectType: 'Industrial',
    leadSource: 'Prospección',
    status: 'Lead',
    assignedSalesperson: 'Carlos Méndez',
    notes: 'Posible expansión de centro de distribución para 2026.',
    createdAt: '2025-06-02',
    lastContact: '2025-06-04',
    timeline: [],
  },
  {
    id: 'torres-del-mar',
    company: 'Torres del Mar',
    contact: 'Andrea Fuentes',
    phone: '+52 998 214 9037',
    email: 'andrea.fuentes@torresdelmar.mx',
    address: 'Av. Bonampak 12, Zona Hotelera, Cancún, Q. Roo',
    rfc: 'TDM160718R62',
    projectType: 'Residencial',
    leadSource: 'Referido',
    status: 'Proposal',
    assignedSalesperson: 'Lucía Castillo',
    notes: 'Condominio vertical de alta gama. Propuesta en revisión legal.',
    createdAt: '2025-03-14',
    lastContact: '2025-06-03',
    timeline: [
      { id: 'tdm-1', type: 'quote', title: 'Versión final enviada', description: 'Se envió la propuesta final con calendario de fases.', date: '2025-06-03', author: 'Lucía Castillo' },
    ],
  },
  {
    id: 'universidad-metropolitana',
    company: 'Universidad Metropolitana',
    contact: 'Óscar Valdés',
    phone: '+52 55 9130 2286',
    email: 'oscar.valdes@umetropolitana.edu.mx',
    address: 'Av. Universidad 1870, Copilco, CDMX',
    rfc: 'UME150923T48',
    projectType: 'Infraestructura',
    leadSource: 'Evento',
    status: 'Active',
    assignedSalesperson: 'Ana Ruiz',
    notes: 'Programa anual de mantenimiento y ampliación de campus.',
    createdAt: '2023-08-11',
    lastContact: '2025-05-30',
    timeline: [
      { id: 'um-1', type: 'meeting', title: 'Planeación anual', description: 'Se definieron prioridades de obra para el segundo semestre.', date: '2025-05-30', author: 'Ana Ruiz' },
    ],
  },
  {
    id: 'mercados-urbanos',
    company: 'Mercados Urbanos MX',
    contact: 'Gabriela Santos',
    phone: '+52 33 1204 6672',
    email: 'gabriela.santos@mercadosurbanos.mx',
    address: 'Av. Patria 880, Jardines Universidad, Zapopan, Jal.',
    rfc: 'MUM230207H56',
    projectType: 'Comercial',
    leadSource: 'Redes sociales',
    status: 'Qualified',
    assignedSalesperson: 'Miguel García',
    notes: 'Red de tres mercados gastronómicos con una primera sede prioritaria.',
    createdAt: '2025-05-02',
    lastContact: '2025-05-28',
    timeline: [
      { id: 'mu-1', type: 'call', title: 'Alcance confirmado', description: 'Se confirmó el programa arquitectónico de la primera sede.', date: '2025-05-28', author: 'Miguel García' },
    ],
  },
]

export function getCustomers(): Customer[] {
  return customerSamples
}

export function getCustomerById(id: string): Customer | undefined {
  return customerSamples.find((customer) => customer.id === id)
}
