'use client'

import { FormEvent, useState } from 'react'
import { BookOpen, CloudSun, Eye, EyeOff, Pencil, Plus, Trash2, Users, X } from 'lucide-react'
import type { Project, ProjectDailyLog } from '@/features/projects/types/project'
import { formatProjectDate } from '@/features/projects/utils/projectUtils'
import { Card, CardHeader } from '@/components/ui/Card'
import { readProjectById, readProjects, writeProjects } from '@/features/projects/services/projectStorage'

type Props={project:Project}
type Draft={date:string;author:string;weather:string;crew:string;summary:string;blockers:string;visibleToClient:boolean}
const emptyDraft=():Draft=>({date:new Date().toISOString().slice(0,10),author:'',weather:'',crew:'',summary:'',blockers:'',visibleToClient:false})

export function DailyLog({project}:Props){
 const[current,setCurrent]=useState(project);const[open,setOpen]=useState(false);const[editingId,setEditingId]=useState<string|null>(null);const[draft,setDraft]=useState<Draft>(emptyDraft)
 function persist(dailyLogs:ProjectDailyLog[]){const next=readProjects().map(p=>p.id===current.id?{...p,dailyLogs}:p);writeProjects(next);setCurrent(readProjectById(current.id)??{...current,dailyLogs})}
 function create(){setEditingId(null);setDraft(emptyDraft());setOpen(true)}
 function edit(log:ProjectDailyLog){setEditingId(log.id);setDraft({date:log.date,author:log.author,weather:log.weather,crew:String(log.crew),summary:log.summary,blockers:log.blockers,visibleToClient:log.visibleToClient===true});setOpen(true)}
 function close(){setOpen(false);setEditingId(null);setDraft(emptyDraft())}
 function submit(e:FormEvent){e.preventDefault();if(!draft.date||!draft.summary.trim())return;const values={date:draft.date,author:draft.author.trim()||'NEDVI Constructora',weather:draft.weather.trim()||'No especificado',crew:Math.max(0,Number(draft.crew)||0),summary:draft.summary.trim(),blockers:draft.blockers.trim(),visibleToClient:draft.visibleToClient};if(editingId)persist(current.dailyLogs.map(x=>x.id===editingId?{...x,...values}:x));else persist([{id:crypto.randomUUID(),...values},...current.dailyLogs]);close()}
 function remove(log:ProjectDailyLog){if(window.confirm(`¿Eliminar el reporte del ${formatProjectDate(log.date)}?`))persist(current.dailyLogs.filter(x=>x.id!==log.id))}
 function toggle(log:ProjectDailyLog){persist(current.dailyLogs.map(x=>x.id===log.id?{...x,visibleToClient:x.visibleToClient!==true}:x))}
 return <Card className="overflow-hidden"><CardHeader title="Reportes de avance" description={`${current.dailyLogs.length} reportes · ${current.dailyLogs.filter(x=>x.visibleToClient===true).length} publicados al cliente`} action={<button type="button" onClick={create} className="inline-flex h-9 items-center gap-2 rounded-xl bg-[#163DFF] px-3 text-xs font-semibold text-white"><Plus size={14}/>Nuevo reporte</button>}/>
 {open?<form onSubmit={submit} className="border-t border-white/[0.07] p-5 sm:p-6"><div className="mb-5 flex items-start justify-between"><div><p className="text-sm font-semibold text-white">{editingId?'Editar reporte':'Nuevo reporte de avance'}</p><p className="mt-1 text-xs text-[#9CA3AF]">Registra las actividades de obra y decide si el cliente podrá consultarlas.</p></div><button type="button" onClick={close} className="p-2 text-[#9CA3AF]"><X size={16}/></button></div><div className="grid gap-4 sm:grid-cols-2"><Field label="Fecha"><input required type="date" value={draft.date} onChange={e=>setDraft({...draft,date:e.target.value})} className="report-input"/></Field><Field label="Responsable"><input value={draft.author} onChange={e=>setDraft({...draft,author:e.target.value})} className="report-input" placeholder="Ej. Pedro García"/></Field><Field label="Clima"><input value={draft.weather} onChange={e=>setDraft({...draft,weather:e.target.value})} className="report-input" placeholder="Ej. Soleado, 24 °C"/></Field><Field label="Personal en obra"><input type="number" min="0" value={draft.crew} onChange={e=>setDraft({...draft,crew:e.target.value})} className="report-input" placeholder="0"/></Field><Field label="Actividades realizadas" className="sm:col-span-2"><textarea required value={draft.summary} onChange={e=>setDraft({...draft,summary:e.target.value})} className="report-area" placeholder="Describe el avance y los trabajos realizados..."/></Field><Field label="Incidencias / observaciones" className="sm:col-span-2"><textarea value={draft.blockers} onChange={e=>setDraft({...draft,blockers:e.target.value})} className="report-area" placeholder="Retrasos, materiales pendientes, observaciones de seguridad, etc."/></Field><label className="sm:col-span-2 flex items-center justify-between rounded-xl border border-white/[0.08] px-4 py-3"><span><span className="block text-xs font-semibold text-white">Publicar al cliente</span><span className="text-[11px] text-[#9CA3AF]">El reporte aparecerá en su Portal del Cliente.</span></span><input type="checkbox" checked={draft.visibleToClient} onChange={e=>setDraft({...draft,visibleToClient:e.target.checked})} className="h-4 w-4 accent-[#163DFF]"/></label></div><div className="mt-5 flex justify-end gap-3"><button type="button" onClick={close} className="h-10 rounded-xl border border-white/[0.09] px-4 text-xs text-[#d5d7df]">Cancelar</button><button className="h-10 rounded-xl bg-[#163DFF] px-5 text-xs font-semibold text-white">Guardar reporte</button></div></form>:null}
 <div className="divide-y divide-white/[0.05] border-t border-white/[0.07]">{current.dailyLogs.length?current.dailyLogs.map(log=><article key={log.id} className="p-5 sm:p-6"><div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><p className="text-xs font-semibold text-white">{formatProjectDate(log.date)}</p><span className={`rounded-full px-2 py-0.5 text-[9px] font-semibold ${log.visibleToClient===true?'bg-emerald-500/15 text-emerald-400':'bg-white/[0.05] text-[#9CA3AF]'}`}>{log.visibleToClient===true?'Publicado al cliente':'Solo NEDVI'}</span></div><p className="mt-1 text-[10px] text-[#646873]">Responsable: {log.author||'NEDVI Constructora'}</p><div className="mt-4 flex flex-wrap gap-2"><span className="inline-flex items-center gap-2 rounded-xl bg-[#17181C] px-3 py-2 text-[11px] text-[#9CA3AF]"><CloudSun size={14} className="text-[#7187ff]"/>{log.weather||'No especificado'}</span><span className="inline-flex items-center gap-2 rounded-xl bg-[#17181C] px-3 py-2 text-[11px] text-[#9CA3AF]"><Users size={14} className="text-[#7187ff]"/>{log.crew} personas</span></div><p className="mt-4 text-xs leading-6 text-[#d5d7df]">{log.summary}</p>{log.blockers?<div className="mt-4 rounded-xl border border-amber-400/15 bg-amber-400/[0.06] p-3"><p className="text-[10px] font-semibold uppercase tracking-[0.1em] text-amber-300">Incidencias / observaciones</p><p className="mt-1 text-xs leading-5 text-[#d8c5a1]">{log.blockers}</p></div>:null}</div><div className="flex shrink-0 gap-1"><Action title={log.visibleToClient===true?'Ocultar al cliente':'Publicar al cliente'} onClick={()=>toggle(log)} icon={log.visibleToClient===true?EyeOff:Eye}/><Action title="Editar" onClick={()=>edit(log)} icon={Pencil}/><Action title="Eliminar" onClick={()=>remove(log)} icon={Trash2} danger/></div></div></article>):<div className="py-10 text-center"><BookOpen className="mx-auto text-[#7187ff]" size={24}/><p className="mt-3 text-sm font-semibold text-white">Todavía no hay reportes</p><p className="mt-1 text-xs text-[#646873]">Registra el primer avance de este proyecto.</p></div>}</div><style jsx>{`.report-input{height:44px;width:100%;border-radius:12px;border:1px solid rgba(255,255,255,.09);background:#17181C;padding:0 12px;font-size:14px;color:white;outline:none}.report-area{min-height:96px;width:100%;border-radius:12px;border:1px solid rgba(255,255,255,.09);background:#17181C;padding:12px;font-size:14px;color:white;outline:none;resize:vertical}`}</style></Card>}
function Field({label,children,className=''}:{label:string;children:React.ReactNode;className?:string}){return <label className={className}><span className="mb-2 block text-[10px] font-semibold uppercase tracking-wider text-[#646873]">{label}</span>{children}</label>}
function Action({title,onClick,icon:Icon,danger=false}:{title:string;onClick:()=>void;icon:typeof Eye;danger?:boolean}){return <button type="button" title={title} onClick={onClick} className={`inline-flex h-8 w-8 items-center justify-center rounded-lg border border-white/[0.08] ${danger?'text-red-400':'text-[#9CA3AF] hover:text-white'}`}><Icon size={14}/></button>}
