import Link from 'next/link'
import { ArrowUpRight, CalendarDays, MapPin, Trash2 } from 'lucide-react'
import type { Project } from '@/features/projects/types/project'
import { formatCurrency, formatProjectDate, getProjectInitials } from '@/features/projects/utils/projectUtils'
import { Card } from '@/components/ui/Card'
import { ProgressBar } from '@/features/projects/components/ProgressBar'
import { ProjectStatusBadge } from '@/features/projects/components/ProjectStatusBadge'

type ProjectCardProps = { project: Project; onDelete: (project: Project) => void; deleting?: boolean }

export function ProjectCard({ project, onDelete, deleting = false }: ProjectCardProps) {
  return <Card className="overflow-hidden transition duration-200 hover:-translate-y-0.5 hover:border-white/[0.14]"><div className="flex items-start justify-between gap-3 border-b border-white/[0.06] p-5"><div className="flex min-w-0 items-center gap-3"><span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-[#163DFF]/[0.14] text-xs font-semibold text-[#9aabff]">{getProjectInitials(project)}</span><div className="min-w-0"><Link href={`/projects/${project.id}`} className="block truncate text-sm font-semibold text-white transition hover:text-[#91a2ff]">{project.name}</Link><p className="mt-1 truncate text-xs text-[#9CA3AF]">{project.client}</p></div></div><ProjectStatusBadge status={project.status} /></div><div className="space-y-4 p-5"><div><div className="mb-2 flex items-center justify-between"><span className="text-[10px] font-semibold uppercase tracking-[0.12em] text-[#646873]">Avance</span><span className="text-xs font-semibold text-white">{project.progress}%</span></div><ProgressBar value={project.progress} showLabel={false} size="sm" /></div><div className="grid grid-cols-2 gap-3"><div><p className="text-[10px] uppercase tracking-[0.1em] text-[#646873]">Presupuesto</p><p className="mt-1 text-xs font-medium text-[#d5d7df]">{formatCurrency(project.budget)}</p></div><div><p className="text-[10px] uppercase tracking-[0.1em] text-[#646873]">Finalización</p><p className="mt-1 text-xs font-medium text-[#d5d7df]">{formatProjectDate(project.estimatedCompletion)}</p></div></div><div className="space-y-2 border-t border-white/[0.06] pt-4 text-[11px] text-[#646873]"><p className="flex items-center gap-2 truncate"><MapPin size={13} />{project.address}</p><p className="flex items-center gap-2"><CalendarDays size={13} />Responsable: {project.manager}</p></div><div className="flex items-center justify-between gap-3"><Link href={`/projects/${project.id}`} className="inline-flex items-center gap-1 text-xs font-semibold text-[#7187ff] transition hover:text-white">Abrir proyecto <ArrowUpRight size={13} /></Link><button type="button" onClick={() => onDelete(project)} disabled={deleting} className="inline-flex items-center gap-1.5 rounded-lg border border-red-500/20 bg-red-500/5 px-2.5 py-1.5 text-xs font-semibold text-red-400 transition hover:bg-red-500/10 disabled:cursor-wait disabled:opacity-50"><Trash2 size={13} />{deleting ? 'Eliminando...' : 'Eliminar'}</button></div></div></Card>
}
