'use client'

import { ChangeEvent, FormEvent, useRef, useState } from 'react'
import { Download, Eye, EyeOff, FileSpreadsheet, FileText, FolderOpen, Pencil, Plus, Trash2, Upload, X } from 'lucide-react'
import { Card, CardHeader } from '@/components/ui/Card'
import { readProjectById, readProjects, writeProjects } from '@/features/projects/services/projectStorage'
import type { Project, ProjectDocument } from '@/features/projects/types/project'

type Props = { project: Project }
type Draft = { name:string; category:string; description:string; updatedAt:string; visibleToClient:boolean; fileUrl:string; fileName:string; type:ProjectDocument['type']; size:string }
const emptyDraft=():Draft=>({name:'',category:'',description:'',updatedAt:new Date().toISOString().slice(0,10),visibleToClient:false,fileUrl:'',fileName:'',type:'PDF',size:''})

function fileType(file:File):ProjectDocument['type']{const n=file.name.toLowerCase();if(n.endsWith('.pdf'))return'PDF';if(n.endsWith('.doc')||n.endsWith('.docx'))return'DOCX';if(n.endsWith('.xls')||n.endsWith('.xlsx'))return'XLSX';return'OTHER'}
function fileSize(bytes:number){if(bytes<1024)return`${bytes} B`;if(bytes<1024*1024)return`${(bytes/1024).toFixed(1)} KB`;return`${(bytes/1024/1024).toFixed(1)} MB`}

export function ProjectDocuments({project}:Props){
 const[current,setCurrent]=useState(project);const[open,setOpen]=useState(false);const[editingId,setEditingId]=useState<string|null>(null);const[draft,setDraft]=useState<Draft>(emptyDraft);const fileRef=useRef<HTMLInputElement>(null)
 function persist(documents:ProjectDocument[]){const next=readProjects().map(p=>p.id===current.id?{...p,documents}:p);writeProjects(next);setCurrent(readProjectById(current.id)??{...current,documents})}
 function create(){setEditingId(null);setDraft(emptyDraft());setOpen(true)}
 function edit(doc:ProjectDocument){setEditingId(doc.id);setDraft({name:doc.name,category:doc.category??'',description:doc.description??'',updatedAt:doc.updatedAt||new Date().toISOString().slice(0,10),visibleToClient:doc.visibleToClient===true,fileUrl:doc.fileUrl??'',fileName:doc.fileName??doc.name,type:doc.type,size:doc.size});setOpen(true)}
 function close(){setOpen(false);setEditingId(null);setDraft(emptyDraft())}
 function selectFile(e:ChangeEvent<HTMLInputElement>){const file=e.target.files?.[0];if(!file)return;const reader=new FileReader();reader.onload=()=>{if(typeof reader.result==='string')setDraft(v=>({...v,fileUrl:reader.result as string,fileName:file.name,type:fileType(file),size:fileSize(file.size),name:v.name||file.name.replace(/\.[^.]+$/,'')}))};reader.readAsDataURL(file)}
 function submit(e:FormEvent){e.preventDefault();if(!draft.name.trim()||!draft.fileUrl)return;const values={name:draft.name.trim(),category:draft.category.trim(),description:draft.description.trim(),updatedAt:draft.updatedAt,visibleToClient:draft.visibleToClient,fileUrl:draft.fileUrl,fileName:draft.fileName,type:draft.type,size:draft.size};if(editingId)persist(current.documents.map(d=>d.id===editingId?{...d,...values}:d));else persist([{id:crypto.randomUUID(),...values},...current.documents]);close()}
 function remove(doc:ProjectDocument){if(window.confirm(`¿Eliminar el documento “${doc.name}”?`))persist(current.documents.filter(d=>d.id!==doc.id))}
 function toggle(doc:ProjectDocument){persist(current.documents.map(d=>d.id===doc.id?{...d,visibleToClient:d.visibleToClient!==true}:d))}
 function download(doc:ProjectDocument){if(!doc.fileUrl)return;const a=document.createElement('a');a.href=doc.fileUrl;a.download=doc.fileName||doc.name;document.body.appendChild(a);a.click();a.remove()}
 return <Card className="overflow-hidden"><CardHeader title="Documentos del proyecto" description={`${current.documents.length} documentos · ${current.documents.filter(d=>d.visibleToClient===true).length} visibles para cliente`} action={<button type="button" onClick={create} className="inline-flex h-9 items-center gap-2 rounded-xl bg-[#163DFF] px-3 text-xs font-semibold text-white"><Plus size={14}/>Nuevo documento</button>}/>
 {open?<form onSubmit={submit} className="border-t border-white/[0.07] p-5 sm:p-6"><div className="mb-5 flex items-center justify-between"><div><p className="text-sm font-semibold text-white">{editingId?'Editar documento':'Nuevo documento'}</p><p className="mt-1 text-xs text-[#9CA3AF]">Carga un archivo y controla si estará disponible en el Portal del Cliente.</p></div><button type="button" onClick={close} className="p-2 text-[#9CA3AF]"><X size={16}/></button></div>
 <div className="grid gap-4 sm:grid-cols-2"><label className="sm:col-span-2"><span className="mb-2 block text-[10px] font-semibold uppercase tracking-wider text-[#646873]">Archivo</span><input ref={fileRef} type="file" className="hidden" accept=".pdf,.doc,.docx,.xls,.xlsx" onChange={selectFile}/><button type="button" onClick={()=>fileRef.current?.click()} className="flex min-h-20 w-full items-center justify-center gap-3 rounded-xl border border-dashed border-white/[0.14] bg-white/[0.025] text-xs text-[#9CA3AF]"><Upload size={18}/>{draft.fileName||'Seleccionar PDF, Word o Excel'}</button></label>
 <Field label="Nombre"><input required value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})} className="input-doc" placeholder="Ej. Plano arquitectónico"/></Field><Field label="Categoría"><input value={draft.category} onChange={e=>setDraft({...draft,category:e.target.value})} className="input-doc" placeholder="Ej. Planos, Contratos, Reportes"/></Field><Field label="Fecha"><input type="date" value={draft.updatedAt} onChange={e=>setDraft({...draft,updatedAt:e.target.value})} className="input-doc"/></Field><label className="flex items-center justify-between rounded-xl border border-white/[0.08] px-4 py-3"><span><span className="block text-xs font-semibold text-white">Visible para cliente</span><span className="text-[11px] text-[#9CA3AF]">Apagado = Solo NEDVI</span></span><input type="checkbox" checked={draft.visibleToClient} onChange={e=>setDraft({...draft,visibleToClient:e.target.checked})} className="h-4 w-4 accent-[#163DFF]"/></label><Field label="Descripción" className="sm:col-span-2"><textarea value={draft.description} onChange={e=>setDraft({...draft,description:e.target.value})} className="min-h-24 w-full rounded-xl border border-white/[0.09] bg-[#17181C] p-3 text-sm text-white outline-none"/></Field></div>
 <div className="mt-5 flex justify-end gap-3"><button type="button" onClick={close} className="h-10 rounded-xl border border-white/[0.09] px-4 text-xs text-[#d5d7df]">Cancelar</button><button disabled={!draft.name.trim()||!draft.fileUrl} className="h-10 rounded-xl bg-[#163DFF] px-5 text-xs font-semibold text-white disabled:opacity-40">Guardar documento</button></div></form>:null}
 <div className="divide-y divide-white/[0.05] border-t border-white/[0.07] px-5 sm:px-6">{current.documents.length?current.documents.map(doc=>{const Icon=doc.type==='XLSX'?FileSpreadsheet:FileText;return <div key={doc.id} className="flex items-center gap-3 py-4"><span className="flex h-10 w-10 items-center justify-center rounded-lg bg-[#163DFF]/10 text-[#7187ff]"><Icon size={17}/></span><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><p className="truncate text-xs font-semibold text-[#d5d7df]">{doc.name}</p><span className={`rounded-full px-2 py-0.5 text-[9px] font-semibold ${doc.visibleToClient===true?'bg-emerald-500/15 text-emerald-400':'bg-white/[0.05] text-[#9CA3AF]'}`}>{doc.visibleToClient===true?'Visible para cliente':'Solo NEDVI'}</span></div><p className="mt-1 text-[10px] text-[#646873]">{[doc.category,doc.type,doc.size,doc.updatedAt].filter(Boolean).join(' · ')}</p>{doc.description?<p className="mt-1 truncate text-[11px] text-[#9CA3AF]">{doc.description}</p>:null}</div><div className="flex gap-1"><Action title={doc.visibleToClient===true?'Ocultar al cliente':'Mostrar al cliente'} onClick={()=>toggle(doc)} icon={doc.visibleToClient===true?EyeOff:Eye}/>{doc.fileUrl?<Action title="Descargar" onClick={()=>download(doc)} icon={Download}/>:null}<Action title="Editar" onClick={()=>edit(doc)} icon={Pencil}/><Action title="Eliminar" onClick={()=>remove(doc)} icon={Trash2} danger/></div></div>}):<div className="py-10 text-center"><FolderOpen className="mx-auto text-[#7187ff]" size={24}/><p className="mt-3 text-sm font-semibold text-white">Todavía no hay documentos</p><p className="mt-1 text-xs text-[#646873]">Agrega el primer archivo del proyecto.</p></div>}</div>
 <style jsx>{`.input-doc{height:44px;width:100%;border-radius:12px;border:1px solid rgba(255,255,255,.09);background:#17181C;padding:0 12px;font-size:14px;color:white;outline:none}`}</style></Card>}
function Field({label,children,className=''}:{label:string;children:React.ReactNode;className?:string}){return <label className={className}><span className="mb-2 block text-[10px] font-semibold uppercase tracking-wider text-[#646873]">{label}</span>{children}</label>}
function Action({title,onClick,icon:Icon,danger=false}:{title:string;onClick:()=>void;icon:typeof Eye;danger?:boolean}){return <button type="button" title={title} onClick={onClick} className={`inline-flex h-8 w-8 items-center justify-center rounded-lg border border-white/[0.08] ${danger?'text-red-400':'text-[#9CA3AF] hover:text-white'}`}><Icon size={14}/></button>}
