import Link from 'next/link'
import { ArrowDown, ArrowUp, ArrowUpDown, CalendarDays, MoreHorizontal } from 'lucide-react'
import type { Project, ProjectSortKey, SortDirection } from '@/features/projects/types/project'
import { formatCurrency, formatProjectDate, getProjectInitials } from '@/features/projects/utils/projectUtils'
import { ProgressBar } from '@/features/projects/components/ProgressBar'
import { ProjectStatusBadge } from '@/features/projects/components/ProjectStatusBadge'

type ProjectTableProps = { projects: Project[]; sortKey: ProjectSortKey; sortDirection: SortDirection; onSort: (key: ProjectSortKey) => void }

type SortableColumnProps = { label: string; sortKey: ProjectSortKey; activeKey: ProjectSortKey; direction: SortDirection; onSort: (key: ProjectSortKey) => void }

function SortableColumn({ label, sortKey, activeKey, direction, onSort }: SortableColumnProps) {
  const isActive = sortKey === activeKey
  return <button type="button" onClick={() => onSort(sortKey)} className="inline-flex items-center gap-1.5 text-[10px] font-semibold uppercase tracking-[0.1em] text-[#646873] transition hover:text-white">{label}{isActive ? (direction === 'asc' ? <ArrowUp size={12} /> : <ArrowDown size={12} />) : <ArrowUpDown size={12} />}</button>
}

export function ProjectTable({ projects, sortKey, sortDirection, onSort }: ProjectTableProps) {
  return <div className="hidden overflow-hidden rounded-2xl border border-white/[0.07] bg-[#20232A] shadow-[0_16px_50px_rgba(0,0,0,0.16)] lg:block"><div className="overflow-x-auto"><table className="w-full min-w-[980px] border-collapse text-left"><thead className="border-b border-white/[0.06] bg-white/[0.015]"><tr><th className="px-6 py-4"><SortableColumn label="Project" sortKey="name" activeKey={sortKey} direction={sortDirection} onSort={onSort} /></th><th className="px-4 py-4"><SortableColumn label="Client" sortKey="client" activeKey={sortKey} direction={sortDirection} onSort={onSort} /></th><th className="px-4 py-4"><SortableColumn label="Progress" sortKey="progress" activeKey={sortKey} direction={sortDirection} onSort={onSort} /></th><th className="px-4 py-4"><span className="text-[10px] font-semibold uppercase tracking-[0.1em] text-[#646873]">Budget</span></th><th className="px-4 py-4"><SortableColumn label="Status" sortKey="status" activeKey={sortKey} direction={sortDirection} onSort={onSort} /></th><th className="px-4 py-4"><SortableColumn label="Completion" sortKey="estimatedCompletion" activeKey={sortKey} direction={sortDirection} onSort={onSort} /></th><th className="w-12 px-4 py-4"><span className="sr-only">Actions</span></th></tr></thead><tbody className="divide-y divide-white/[0.05]">{projects.map((project) => <tr className="group transition hover:bg-white/[0.025]" key={project.id}><td className="px-6 py-4"><div className="flex items-center gap-3"><span className="flex h-9 w-9 shrink-0 items-center justify-center rounded-lg bg-[#163DFF]/[0.12] text-[10px] font-semibold text-[#9aabff]">{getProjectInitials(project)}</span><div className="min-w-0"><Link href={`/projects/${project.id}`} className="block max-w-[210px] truncate text-xs font-semibold text-white transition hover:text-[#91a2ff]">{project.name}</Link><p className="mt-1 text-[10px] text-[#646873]">{project.projectType}</p></div></div></td><td className="px-4 py-4 text-xs text-[#d5d7df]">{project.client}</td><td className="w-44 px-4 py-4"><ProgressBar value={project.progress} size="sm" /></td><td className="px-4 py-4 text-xs font-medium text-[#d5d7df]">{formatCurrency(project.budget)}</td><td className="px-4 py-4"><ProjectStatusBadge status={project.status} /></td><td className="px-4 py-4"><p className="text-xs text-[#d5d7df]">{formatProjectDate(project.estimatedCompletion)}</p><div className="mt-1 flex items-center gap-1 text-[10px] text-[#646873]"><CalendarDays size={11} />{project.manager}</div></td><td className="px-4 py-4"><Link href={`/projects/${project.id}`} className="flex rounded-lg p-2 text-[#646873] transition hover:bg-white/[0.06] hover:text-white" aria-label={`Open ${project.name}`}><MoreHorizontal size={17} /></Link></td></tr>)}</tbody></table></div></div>
}
