import { ExternalLink, MapPin, Navigation } from 'lucide-react'
import type { Project } from '@/features/projects/types/project'
import { Card, CardHeader } from '@/components/ui/Card'

type ProjectMapProps = { project: Pick<Project, 'address' | 'latitude' | 'longitude' | 'name'> }

export function ProjectMap({ project }: ProjectMapProps) {
  return <Card className="overflow-hidden"><CardHeader title="Project location" description="Site coordinates and address" action={<Navigation size={17} className="text-[#7187ff]" />} /><div className="p-5 sm:p-6"><div className="relative h-48 overflow-hidden rounded-xl border border-white/[0.07] bg-[#17181C]" aria-label={`Map location for ${project.name}`} role="img"><div className="absolute inset-0 opacity-40" style={{ backgroundImage: 'linear-gradient(45deg, transparent 46%, rgba(255,255,255,0.06) 47%, rgba(255,255,255,0.06) 48%, transparent 49%), linear-gradient(-45deg, transparent 46%, rgba(255,255,255,0.04) 47%, rgba(255,255,255,0.04) 48%, transparent 49%)', backgroundSize: '56px 56px' }} /><div className="absolute left-[52%] top-[44%] flex -translate-x-1/2 -translate-y-full flex-col items-center"><span className="flex h-9 w-9 items-center justify-center rounded-full bg-[#163DFF] text-white shadow-[0_0_0_7px_rgba(22,61,255,0.18),0_8px_20px_rgba(0,0,0,0.4)]"><MapPin size={18} fill="currentColor" /></span><span className="mt-2 whitespace-nowrap rounded-md border border-white/[0.08] bg-[#20232A]/90 px-2 py-1 text-[10px] font-semibold text-white backdrop-blur">{project.name}</span></div><div className="absolute bottom-3 left-3 rounded-md border border-white/[0.08] bg-[#20232A]/90 px-2 py-1 text-[10px] text-[#9CA3AF] backdrop-blur">GPS verified</div></div><div className="mt-4 flex items-start justify-between gap-4"><div className="flex gap-2 text-xs text-[#9CA3AF]"><MapPin size={14} className="mt-0.5 shrink-0 text-[#7187ff]" /><span>{project.address}</span></div><a href={`https://www.google.com/maps?q=${project.latitude},${project.longitude}`} target="_blank" rel="noreferrer" className="shrink-0 rounded-lg p-1.5 text-[#646873] transition hover:bg-white/[0.05] hover:text-white" aria-label="Open project location in maps"><ExternalLink size={14} /></a></div><p className="mt-3 text-[10px] text-[#646873]">{project.latitude.toFixed(4)}, {project.longitude.toFixed(4)}</p></div></Card>
}
