'use client'

import { FormEvent, useState } from 'react'
import { Check, Circle, Eye, EyeOff, ListChecks, Pencil, Plus, Trash2, X } from 'lucide-react'
import type { Project, ProjectTask } from '@/features/projects/types/project'
import { formatProjectDate } from '@/features/projects/utils/projectUtils'
import { Card, CardHeader } from '@/components/ui/Card'
import { readProjectById, readProjects, writeProjects } from '@/features/projects/services/projectStorage'

type Props={project:Project}
type Draft={title:string;assignee:string;dueDate:string;priority:ProjectTask['priority'];completed:boolean;visibleToClient:boolean}
const emptyDraft=():Draft=>({title:'',assignee:'',dueDate:new Date().toISOString().slice(0,10),priority:'Medium',completed:false,visibleToClient:false})
const priorityStyles={Low:'text-[#9CA3AF]',Medium:'text-sky-300',High:'text-amber-300'}
const priorityLabel={Low:'Baja',Medium:'Media',High:'Alta'}

export function TaskList({project}:Props){
 const[current,setCurrent]=useState(project);const[open,setOpen]=useState(false);const[editingId,setEditingId]=useState<string|null>(null);const[draft,setDraft]=useState<Draft>(emptyDraft)
 function persist(tasks:ProjectTask[]){const next=readProjects().map(p=>p.id===current.id?{...p,tasks}:p);writeProjects(next);setCurrent(readProjectById(current.id)??{...current,tasks})}
 function create(){setEditingId(null);setDraft(emptyDraft());setOpen(true)}
 function edit(task:ProjectTask){setEditingId(task.id);setDraft({title:task.title,assignee:task.assignee,dueDate:task.dueDate,priority:task.priority,completed:task.completed,visibleToClient:task.visibleToClient===true});setOpen(true)}
 function close(){setOpen(false);setEditingId(null);setDraft(emptyDraft())}
 function submit(e:FormEvent){e.preventDefault();if(!draft.title.trim())return;const values={...draft,title:draft.title.trim(),assignee:draft.assignee.trim()||'NEDVI'};if(editingId)persist(current.tasks.map(x=>x.id===editingId?{...x,...values}:x));else persist([...current.tasks,{id:crypto.randomUUID(),...values}]);close()}
 function toggleComplete(task:ProjectTask){persist(current.tasks.map(x=>x.id===task.id?{...x,completed:!x.completed}:x))}
 function toggleVisibility(task:ProjectTask){persist(current.tasks.map(x=>x.id===task.id?{...x,visibleToClient:x.visibleToClient!==true}:x))}
 function remove(task:ProjectTask){if(window.confirm(`¿Eliminar la actividad "${task.title}"?`))persist(current.tasks.filter(x=>x.id!==task.id))}
 return <Card className="overflow-hidden"><CardHeader title="Actividades del proyecto" description={`${current.tasks.filter(x=>!x.completed).length} pendientes · ${current.tasks.filter(x=>x.visibleToClient===true).length} visibles al cliente`} action={<button type="button" onClick={create} className="inline-flex h-9 items-center gap-2 rounded-xl bg-[#163DFF] px-3 text-xs font-semibold text-white"><Plus size={14}/>Nueva actividad</button>}/>
 {open?<form onSubmit={submit} className="border-t border-white/[0.07] p-5 sm:p-6"><div className="mb-5 flex items-start justify-between"><div><p className="text-sm font-semibold text-white">{editingId?'Editar actividad':'Nueva actividad'}</p><p className="mt-1 text-xs text-[#9CA3AF]">La misma actividad puede publicarse en el Portal del Cliente.</p></div><button type="button" onClick={close} className="p-2 text-[#9CA3AF]"><X size={16}/></button></div><div className="grid gap-4 sm:grid-cols-2"><Field label="Actividad" className="sm:col-span-2"><input required value={draft.title} onChange={e=>setDraft({...draft,title:e.target.value})} className="task-input" placeholder="Ej. Instalación de estructura metálica"/></Field><Field label="Responsable"><input value={draft.assignee} onChange={e=>setDraft({...draft,assignee:e.target.value})} className="task-input" placeholder="Responsable"/></Field><Field label="Fecha límite"><input type="date" required value={draft.dueDate} onChange={e=>setDraft({...draft,dueDate:e.target.value})} className="task-input"/></Field><Field label="Prioridad"><select value={draft.priority} onChange={e=>setDraft({...draft,priority:e.target.value as ProjectTask['priority']})} className="task-input"><option value="Low">Baja</option><option value="Medium">Media</option><option value="High">Alta</option></select></Field><label className="flex items-center justify-between rounded-xl border border-white/[0.08] px-4 py-3"><span className="text-xs font-semibold text-white">Completada</span><input type="checkbox" checked={draft.completed} onChange={e=>setDraft({...draft,completed:e.target.checked})} className="h-4 w-4 accent-[#163DFF]"/></label><label className="sm:col-span-2 flex items-center justify-between rounded-xl border border-white/[0.08] px-4 py-3"><span><span className="block text-xs font-semibold text-white">Visible para cliente</span><span className="text-[11px] text-[#9CA3AF]">El cliente podrá verla en Próximas actividades.</span></span><input type="checkbox" checked={draft.visibleToClient} onChange={e=>setDraft({...draft,visibleToClient:e.target.checked})} className="h-4 w-4 accent-[#163DFF]"/></label></div><div className="mt-5 flex justify-end gap-3"><button type="button" onClick={close} className="h-10 rounded-xl border border-white/[0.09] px-4 text-xs text-[#d5d7df]">Cancelar</button><button className="h-10 rounded-xl bg-[#163DFF] px-5 text-xs font-semibold text-white">Guardar actividad</button></div></form>:null}
 <div className="divide-y divide-white/[0.05] px-5 sm:px-6">{current.tasks.length?current.tasks.map(task=><div className="flex items-start gap-3 py-4" key={task.id}><button type="button" onClick={()=>toggleComplete(task)} className={`mt-0.5 flex h-5 w-5 shrink-0 items-center justify-center rounded-md border transition ${task.completed?'border-emerald-400 bg-emerald-400 text-[#0B0B0D]':'border-white/[0.14] text-transparent hover:border-[#163DFF] hover:bg-[#163DFF] hover:text-white'}`} title={task.completed?'Reabrir':'Marcar completada'}>{task.completed?<Check size={12}/>:<Circle size={8} fill="currentColor"/>}</button><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><p className={`text-xs font-medium ${task.completed?'text-[#646873] line-through':'text-[#d5d7df]'}`}>{task.title}</p><span className={`rounded-full px-2 py-0.5 text-[9px] font-semibold ${task.visibleToClient===true?'bg-emerald-500/15 text-emerald-400':'bg-white/[0.05] text-[#9CA3AF]'}`}>{task.visibleToClient===true?'Visible al cliente':'Solo NEDVI'}</span></div><p className="mt-1 text-[10px] text-[#646873]">{task.assignee||'NEDVI'} · Vence {formatProjectDate(task.dueDate)}</p></div><span className={`shrink-0 text-[10px] font-semibold ${priorityStyles[task.priority]}`}>{priorityLabel[task.priority]}</span><div className="flex shrink-0 gap-1"><Action title={task.visibleToClient===true?'Ocultar al cliente':'Mostrar al cliente'} onClick={()=>toggleVisibility(task)} icon={task.visibleToClient===true?EyeOff:Eye}/><Action title="Editar" onClick={()=>edit(task)} icon={Pencil}/><Action title="Eliminar" onClick={()=>remove(task)} icon={Trash2} danger/></div></div>):<div className="py-9 text-center"><ListChecks className="mx-auto text-[#7187ff]" size={23}/><p className="mt-3 text-xs text-[#646873]">No hay actividades registradas.</p></div>}</div><style jsx>{`.task-input{height:44px;width:100%;border-radius:12px;border:1px solid rgba(255,255,255,.09);background:#17181C;padding:0 12px;font-size:14px;color:white;outline:none}`}</style></Card>}
function Field({label,children,className=''}:{label:string;children:React.ReactNode;className?:string}){return <label className={className}><span className="mb-2 block text-[10px] font-semibold uppercase tracking-wider text-[#646873]">{label}</span>{children}</label>}
function Action({title,onClick,icon:Icon,danger=false}:{title:string;onClick:()=>void;icon:typeof Eye;danger?:boolean}){return <button type="button" title={title} onClick={onClick} className={`inline-flex h-8 w-8 items-center justify-center rounded-lg border border-white/[0.08] ${danger?'text-red-400':'text-[#9CA3AF] hover:text-white'}`}><Icon size={14}/></button>}
